### ISSUE TITLE
Good prompt for JS/TS generator

### ISSUE THREAD

**Issue by anuragts** [anuragts/codeAI#13]
Write a good openai API prompt for the Javascript generator.

**Comment by Waishnav** [comment]
Hey can you elaborate a bit more??

**Comment by Anurag30112003** [comment]
@Waishnav 
Open AI uses a prompt to create the required result. The more detailed the prompt will be, the better the result.
Read more here https://beta.openai.com/docs/guides/completion/prompt-design
